name: Build Angular App

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Cambia esto si usas otra versión de Node.js

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build --if-present


      # Aquí puedes cambiar 'dist' por el nombre de la carpeta de salida de tu build, si es diferente.
